package strings;

public class StaticStrings {

    public static final String FONT = "Tahoma";

    public static final String ICON_FILE_NAME = "icon.jpg";
    public static final String SETTINGS_FILE_NAME = "settings.conf";
    public static final String RECORDS_FILE_NAME = "records.log";
    public static final String RECORDS_EXTENSION_NAME = "log";

    public static final String LOOKANDFEEL_SETTINGS_LABEL = "lookAndFeel=";
    public static final String NIMBUS = "Nimbus";
    public static final String METAL = "Metal";
    public static final String WINDOWS = "Windows";
    public static final String WINDOWS_CLASSIC = "Windows Classic";
    public static final String MOTIF = "Motif";
    public static final String GTK = "GTK";
    public static final String LOOKANDFEEL_NIMBUS = "javax.swing.plaf.nimbus.NimbusLookAndFeel";
    public static final String LOOKANDFEEL_METAL = "javax.swing.plaf.metal.MetalLookAndFeel";
    public static final String LOOKANDFEEL_WINDOWS = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
    public static final String LOOKANDFEEL_WINDOWS_CLASSIC = "com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel";
    public static final String LOOKANDFEEL_MOTIF = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
    public static final String LOOKANDFEEL_GTK = "com.sun.java.swing.plaf.gtk.GTKLookAndFeel";

    public static final String SETTINGS_FILE_LABEL = "# Autogenerated settings file. Do not touch if you don't know what you're doing";
    public static final String SETTINGS_FILE_NOT_FOUND = "The settings file couldn't be found";
    public static final String SETTINGS_FILE_CANNOT_READ = "Could not read the settings file, possibly due to insufficient permissions";
    public static final String LANGUAGE_SETTINGS_LABEL = "language=";
    public static final String LANGUAGE_EN_CODE = "en";
    public static final String LANGUAGE_ES_CODE = "es";


}
